### ISSUE TITLE
Consider the new support for asset bundling as a way to implement chalice package

### ISSUE THREAD

**Issue by eladb** [alexpulver/cdk-chalice#23]
See [docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-assets.Asset.html#bundling-span-class-api-icon-api-icon-experimental-title-this-api-element-is-experimental-it-may-change-without-notice-span)

**Comment by alexpulver** [comment]
Awesome, will adopt it! Thanks for mentioning, I don't know how I missed https://github.com/aws/aws-cdk/issues/8460 in v1.46.0. Most probably because there was a **ton** of updates ;)

**Comment by alexpulver** [comment]
@eladb should I be worried about backwards compatibility for CDK < v1.46.0 users?

**Comment by alexpulver** [comment]
@eladb, apologies for delay, I finally took a look on this one. There seem to be a misfit between what `Asset` is designed for and `cdk-chalice` flow. I'll describe the flow below, and would be glad to get your thoughts on it.

`cdk-chalice` executes `chalice package` command. This is the command that should run either in Docker (using AWS SAM container image) or locally. The command produces two files: 1/ `deployment.zip` (function code), and 2/ `sam.json` (AWS SAM template). At this point, the template references `deployment.zip` using local path: `"CodeUri": "./deployment.zip"`. 

Once these artifacts are produced, I need to 1/ read `sam.json`, replace occurrences of `"./deployment.zip"` with `Asset` in `sam.json`, and store the result in a new file, e.g. `sam_with_assets.json` (to allow Chalice cache builds) 2/ Use `sam_with_assets.json` with `cloudformation_include.CfnInclude` to include the Chalice AWS SAM template into the broader CDK application.

I can't think of how `Asset` bundling capability can be used for this flow, without making it more complex. Do you have any ideas?
