### ISSUE TITLE
Support for deploying chalice applications that contain authorizer lambda function

### ISSUE THREAD

**Issue by sai-cherukumilli-enview** [alexpulver/cdk-chalice#8]
Wondering if there is support in the library to deploy a `chalice.authorizer`

```  UsageRoutesAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: chalicelib.usage.blueprint_usage.usage_routes_authorizer
      CodeUri: ./deployment.zip
      Tags:
        aws-chalice: version=1.8.0:stage=dev:app=entitlements_service
      Timeout: 60
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - DefaultRole
          - Arn
```

Deploying chalice apps without an authorizer lambda works fine, however, when we have an authorizer, the CodeUri is pointed to ./deployment.zip which is not accepted by AWS CLI as a valid url pattern. 
Here is the error message we get:

``` bash
❌  EntitlementsService-dev failed: Error: Failed to create ChangeSet CDK-71375099-370b-4d97-864d-d2afffd55dac on EntitlementsService-dev: FAILED, Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [UsageRoutesAuthorizer] is invalid. 'CodeUri' is not a valid S3 Uri of the form "s3://bucket/key" with optional versionId query parameter.

Failed to create ChangeSet CDK-71375099-370b-4d97-864d-d2afffd55dac on EntitlementsService-dev: FAILED, Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [UsageRoutesAuthorizer] is invalid. 'CodeUri' is not a valid S3 Uri of the form "s3://bucket/key" with optional versionId query parameter.
```

**Comment by alexpulver** [comment]
@sai-cherukumilli-enview thanks for reporting this! I'll take a look and circle back

**Comment by alexpulver** [comment]
@sai-cherukumilli-enview can you please provide snippets of your Chalice app and construct that lead to the above issue?

As of v0.5.1, Chalice construct looks for any resources of type `AWS::Serverless::Function` and replaces their CodeUri with CDK asset value (S3 bucket and key). See [_update_sam_template](https://github.com/alexpulver/cdk-chalice/blob/v0.5.1/cdk_chalice.py#L140) method for details.

I tried following the example in Chalice [Using Amazon Cognito User Pools](https://chalice.readthedocs.io/en/latest/quickstart.html#using-amazon-cognito-user-pools) documentation, and it only produces security definitions in the resulting SAM template:
```json
"securityDefinitions": {
  "MyPool": {
    "in": "header",
    "type": "apiKey",
    "name": "Authorization",
    "x-amazon-apigateway-authtype": "cognito_user_pools",
    "x-amazon-apigateway-authorizer": {
      "type": "cognito_user_pools",
      "providerARNs": [
        "arn:aws:cognito:...:userpool/name"
      ]
    }
  }
}
```
